-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              10.3.13-MariaDB - mariadb.org binary distribution
-- S.O. server:                  Win64
-- HeidiSQL Versione:            10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dump della struttura del database listino
CREATE DATABASE IF NOT EXISTS `listino` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `listino`;

-- Dump della struttura di tabella listino.listino
CREATE TABLE IF NOT EXISTS `listino` (
  `idnum` varchar(16) NOT NULL,
  `name` varchar(150) NOT NULL,
  `category` varchar(150) NOT NULL,
  `price` double NOT NULL,
  `season` varchar(10) DEFAULT NULL,
  `sellerprice` double NOT NULL,
  PRIMARY KEY (`idnum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dump dei dati della tabella listino.listino: ~305 rows (circa)
/*!40000 ALTER TABLE `listino` DISABLE KEYS */;
INSERT INTO `listino` (`idnum`, `name`, `category`, `price`, `season`, `sellerprice`) VALUES
	('A1', 'tutina ciniglia ellepì', 'Tutina', 7.5, 'Inverno', 4.5),
	('A10', 'tutina ciniglia zucchi ', 'Tutina ', 12.9, 'Inverno', 7.74),
	('A100', 'copripanno bianco ', 'Ghettina', 2.5, 'Estate', 1.63),
	('A101', 'copripanno ricamato ', 'Ghettina', 4.5, 'Estate', 2.93),
	('A102', 'copripanno colorato', 'Ghettina', 3.3, 'Estate', 2.15),
	('A103', 'calzini filo di scozia bianco', 'Calzini', 6.5, 'Estate', 3.25),
	('A104', 'calzini cotone assortito', 'Calzini', 2.5, 'Estate', 1.25),
	('A105', 'calzini cotone ', 'Calzini', 3.5, 'Estate', 1.75),
	('A106', 'calzini cotone ', 'Calzini', 3.5, 'Estate', 1.75),
	('A107', 'calzini cotone multicolor', 'Calzini', 1.8, 'Estate', 0.9),
	('A108', 'calzini cotone traforato', 'Calzini', 2, 'Estate', 1),
	('A109', 'cuffia felpa ambra', 'Cuffia', 6, 'Inverno', 3),
	('A11', 'tutina ciniglia zucchi arcobaleno', 'Tutina', 9.9, 'Inverno', 5.94),
	('A110', 'cuffia felpa bianco', 'Cuffia', 5.5, 'Inverno', 2.75),
	('A111', 'cuffia felpa rigato', 'Cuffia', 7.5, 'Inverno', 3.75),
	('A112', 'cuffia multicolor', 'Cuffia', 4.5, 'Inverno', 2.25),
	('A113', 'cuffia cotone bianco', 'Cuffia', 4, 'Privavera', 2),
	('A114', 'cuffia cotone assortito', 'Cuffia', 6.5, 'Privavera', 3.25),
	('A115', 'cuffia filo di scozia bianco', 'Cuffia', 8, 'Estate', 4),
	('A116', 'cuffia cotone leggero', 'Cuffia', 5, 'Estate', 2.5),
	('A117', 'fascia ombellicale bianco', 'Fascia ombellicale', 8, '', 4.4),
	('A118', 'fascia ombellicale colorato', 'Fascia ombellicale', 6, '', 3.3),
	('A119', 'fascia ombellicale garza', 'Fascia ombellicale', 3, '', 1.65),
	('A12', 'tutina ciniglia zucchi gatto', 'Tutina', 9.9, 'Inverno', 5.94),
	('A120', 'fascia ombellicale rete', 'Fascia ombellicale', 4.5, '', 2.48),
	('A121', 'lenzuolino culla Disney', 'Lenzuolino culla', 15, '', 9.75),
	('A122', 'lenzuolino culla alberi', 'Lenzuolino culla', 13, '', 8.45),
	('A123', 'lenzuolino culla farfalle', 'Lenzuolino culla', 22, '', 14.3),
	('A124', 'lenzuolino culla arcobaleno', 'Lenzuolino culla', 13, '', 8.45),
	('A125', 'lenzuolino culla dinosauri', 'Lenzuolino culla', 9.9, '', 6.44),
	('A126', 'lenzuolino culla fiore', 'Lenzuolino culla', 14, '', 9.1),
	('A127', 'lenzuolino culla papavero', 'Lenzuolino culla', 11.9, '', 7.74),
	('A128', 'lenzuolino culla orsetto', 'Lenzuolino culla', 18, '', 11.7),
	('A129', 'lenzuolino culla cuore', 'Lenzuolino culla', 12, '', 7.8),
	('A13', 'tutina ciniglia zucchi sole', 'Tutina', 9.9, 'Inverno', 5.94),
	('A130', 'lenzuolino culla stelle', 'Lenzuolino culla', 19.9, '', 12.94),
	('A131', 'lenzuolino culla ABC', 'Lenzuolino culla', 7.5, '', 4.88),
	('A132', 'copertina culla felpa', 'Copertina culla', 15, 'Inverno', 9.75),
	('A133', 'copertina culla lana', 'Copertina culla', 22, 'Inverno', 14.3),
	('A134', 'copertina culla verde', 'Copertina culla', 18, 'Inverno', 11.7),
	('A135', 'copertina culla lettere', 'Copertina culla', 15, 'Inverno', 9.75),
	('A136', 'copertina culla fiori', 'Copertina culla', 13, 'Inverno', 8.45),
	('A137', 'copertina culla con bottoni', 'Copertina culla', 22, 'Inverno', 14.3),
	('A138', 'copertina culla ricamata', 'Copertina culla', 25, 'Inverno', 16.25),
	('A139', 'copertina culla pile', 'Copertina culla', 10, 'Inverno', 6.5),
	('A14', 'tutina ciniglia zucchi luna', 'Tutina', 10.9, 'Inverno', 6.54),
	('A140', 'copertina culla lana merinos', 'Copertina culla', 35, 'Inverno', 22.75),
	('A141', 'copri materasso culla spugna', 'Copri materasso culla', 18, '', 11.7),
	('A142', 'copri materasso culla cotone', 'Copri materasso culla', 15, '', 9.75),
	('A143', 'copri materasso culla colorato', 'Copri materasso culla', 12, '', 7.8),
	('A144', 'copri materasso culla bianco', 'Copri materasso culla', 9.9, '', 6.44),
	('A145', 'cuscino culla antisoffoco lattice', 'Cuscino culla', 15, '', 7.5),
	('A146', 'cuscino culla spugna', 'Cuscino culla', 8, '', 4),
	('A147', 'cuscino culla colorato', 'Cuscino culla', 5, '', 2.5),
	('A148', 'materasso culla lattice', 'Materasso culla', 25, '', 12.5),
	('A149', 'materasso culla spugna', 'Materasso culla', 12, '', 6),
	('A15', 'tutina ciniglia zucchi alba', 'Tutina', 16.9, 'Inverno', 10.14),
	('A150', 'materasso culla forato', 'Materasso culla', 16, '', 8),
	('A151', 'materasso culla ovattato', 'Materasso culla', 10, '', 5),
	('A152', 'piumotto culla Disney', 'Piumotto culla', 45, 'Inverno', 29.25),
	('A153', 'piumotto culla orsetto', 'Piumotto culla', 25, 'Inverno', 16.25),
	('A154', 'piumotto culla fiori', 'Piumotto culla', 29.9, 'Inverno', 19.44),
	('A155', 'piumotto culla arcobaleno', 'Piumotto culla', 20, 'Inverno', 13),
	('A156', 'piumotto culla oceano', 'Piumotto culla', 32, 'Inverno', 20.8),
	('A157', 'piumotto culla estate', 'Piumotto culla', 15, 'Inverno', 9.75),
	('A158', 'piumotto culla ricamato', 'Piumotto culla', 55, 'Inverno', 35.75),
	('A159', 'piumotto culla tinta unita', 'Piumotto culla', 22, 'Inverno', 14.3),
	('A16', 'tutina ciniglia mek', 'Tutina', 6.9, 'Inverno', 4.14),
	('A160', 'piumotto culla bianco', 'Piumotto culla', 16.5, 'Inverno', 10.73),
	('A161', 'bavetta Disney', 'Bavetta', 2.5, '', 1.25),
	('A162', 'bavetta arcobaleno', 'Bavetta', 3.5, '', 1.75),
	('A163', 'bavetta ricamata', 'Bavetta', 4, '', 2),
	('A164', 'bavetta ciniglia', 'Bavetta', 2.8, '', 1.4),
	('A165', 'bavetta spugna', 'Bavetta', 1.5, '', 0.75),
	('A166', 'bavetta telata', 'Bavetta', 4, '', 2),
	('A167', 'bavetta abc', 'Bavetta', 2, '', 1),
	('A168', 'bavetta plastificata', 'Bavetta', 3.5, '', 1.75),
	('A169', 'bavetta millerighe', 'Bavetta', 6, '', 3),
	('A17', 'tutina ciniglia mek delux', 'Tutina', 19.9, 'Inverno', 11.94),
	('A170', 'bavetta cotone', 'Bavetta', 1.5, '', 0.75),
	('A171', 'bavetta farfalla', 'Bavetta', 3, '', 1.5),
	('A172', 'bavetta con laccio', 'Bavetta', 6, '', 3),
	('A173', 'bavetta a strappo', 'Bavetta', 5.5, '', 2.75),
	('A174', 'bavetta pvc', 'Bavetta', 1.9, '', 0.95),
	('A175', 'bavetta con bottone', 'Bavetta', 0.8, '', 0.4),
	('A176', 'tutina lana ricamata', 'Tutina', 24.5, 'Inverno', 12.25),
	('A177', 'tutina lana due pezzi', 'Tutina', 22.9, 'Inverno', 11.45),
	('A178', 'tutina lana ellepì verde', 'Tutina', 19.9, 'Inverno', 9.95),
	('A179', 'tutina lana marzotto', 'Tutina', 28.3, 'Inverno', 14.15),
	('A18', 'tutina ciniglia mek alba', 'Tutina', 14.5, 'Inverno', 8.7),
	('A180', 'tutina lana marzotto due pezzi', 'Tutina', 29.9, 'Inverno', 14.95),
	('A181', 'tutina lana orsetto', 'Tutina', 14.3, 'Inverno', 7.15),
	('A182', 'tutina lana arcobaleno', 'Tutina', 14.5, 'Inverno', 7.25),
	('A183', 'tutina lana collo alto ellepì', 'Tutina', 17.2, 'Inverno', 8.6),
	('A184', 'tutina lana con copripanno ellepì', 'Tutina', 22.5, 'Inverno', 11.25),
	('A185', 'tutina con ghettina marzotto', 'Tutina', 9.9, 'Privavera', 4.95),
	('A186', 'tutina con  ricamo marzotto', 'Tutina', 12.9, 'Privavera', 6.45),
	('A187', 'tutina cerimonia marzotto', 'Tutina', 39.9, 'Privavera', 19.95),
	('A188', 'tutina battesimo filo di scozia', 'Tutina', 55.6, 'Privavera', 27.8),
	('A189', 'vestito ciniglia con ricamo', 'Vestitino ', 12.3, 'Inverno', 6.15),
	('A19', 'tutina ciniglia mek  Disney', 'Tutina', 17.5, 'Inverno', 10.5),
	('A190', 'vestito ciniglia Disney', 'vestitino ', 16.9, 'Inverno', 8.45),
	('A191', 'vestito ciniglia fragoline ellepì', 'Vestitino ', 7.8, 'Inverno', 3.9),
	('A192', 'vestito lana con applicazioni', 'Vestitino ', 22.8, 'Inverno', 11.4),
	('A193', 'vestito lana fiori di pesco', 'Vestitino ', 35.6, 'Inverno', 17.8),
	('A194', 'vestito lana cerimonia', 'Vestitino ', 45.9, 'Inverno', 22.95),
	('A195', 'vestito bianco neve', 'Vestitino ', 15.9, 'Inverno', 7.95),
	('A196', 'vestito felpa sportivo', 'Vestitino ', 9.9, 'Inverno', 4.95),
	('A197', 'vestito felpa con giacca', 'Vestitino ', 15.9, 'Inverno', 7.95),
	('A198', 'vestito felpa tigrato', 'Vestitino ', 8.9, 'Inverno', 4.45),
	('A199', 'vestito felpa con girasoli', 'Vestitino ', 14.9, 'Inverno', 7.45),
	('A2', 'tutina ciniglia ellepì ricamata', 'Tutina', 9.99, 'Inverno', 5.99),
	('A20', 'tutina ciniglia mek  Disney', 'Tutina', 17.5, 'Inverno', 10.5),
	('A200', 'vestito felpa con tulipani', 'Vestitino ', 9.9, 'Inverno', 4.95),
	('A201', 'vestito cotone millerighe rosso', 'Vestitino ', 12.9, 'Privavera', 6.45),
	('A202', 'vestito cotone filo di scozia rosa', 'Vestitino ', 22.3, 'Privavera', 11.15),
	('A203', 'vestito in pizzo m/l battesimo', 'Vestitino ', 75.9, 'Privavera', 37.95),
	('A204', 'vestito cotone egiziano battesimo', 'Vestitino ', 55.9, 'Privavera', 27.95),
	('A205', 'scamiciato con camicina', 'Vestitino ', 22.9, 'Privavera', 11.45),
	('A206', 'vestitino m/m cotone verde', 'Vestitino ', 5.9, 'Estate', 2.95),
	('A207', 'vestito cotone con ricamo', 'Vestitino ', 7.8, 'Estate', 3.9),
	('A208', 'vestito disney m/m ricamato', 'Vestitino ', 9.9, 'Estate', 4.95),
	('A209', 'vestito filo di scozia cerimonia', 'Vestitino ', 36.9, 'Estate', 18.45),
	('A21', 'tutina ciniglia mek fiore', 'Tutina', 22.9, 'Inverno', 13.74),
	('A210', 'vestito s/l con copripanno', 'Vestitino ', 6.5, 'Estate', 3.25),
	('A211', 'copertina cotone gialla', 'Copertina culla', 12.9, 'Estate', 6.45),
	('A212', 'copertina cotone ricamata ', 'Copertina culla ', 15, 'Estate', 7.5),
	('A213', 'copertina cotone farfalle', 'Copertina culla ', 11.9, 'Estate', 5.95),
	('A214', 'copertina filo di scozia rosa', 'Copertina culla ', 26.9, 'Estate', 13.45),
	('A215', 'copertina pique giallo', 'Copertina culla ', 9.9, 'Estate', 4.95),
	('A216', 'copertina cotone egiziano viola', 'Copertina culla ', 33.9, 'Estate', 16.95),
	('A217', 'copertina in pizzo francese', 'Copertina culla ', 45.9, 'Estate', 22.95),
	('A218', 'copertina con tulipani rosa', 'Copertina culla ', 11.9, 'Estate', 5.95),
	('A219', 'copertina cotone apina', 'Copertina culla ', 8.5, 'Estate', 4.25),
	('A22', 'tutina ciniglia melbi', 'Tutina', 6, 'Inverno', 3.6),
	('A220', 'copertina  ciniglia rosa', 'Copertina culla ', 13.6, 'Privavera', 6.8),
	('A221', 'copertina ciniglia con rose', 'Copertina culla ', 15.9, 'Privavera', 7.95),
	('A222', 'copertina caldo cotone rosso', 'Copertina culla ', 9.9, 'Privavera', 4.95),
	('A223', 'copertina caldo cotone rosa', 'Copertina culla ', 9.9, 'Privavera', 4.95),
	('A224', 'copertina spugna floreale', 'Copertina culla ', 8.5, 'Privavera', 4.25),
	('A225', 'copertina ciniglia con pizzo', 'Copertina culla ', 22.5, 'Privavera', 11.25),
	('A226', 'copertina ciniglia  cielo', 'Copertina culla ', 12.6, 'Privavera', 6.3),
	('A227', 'copertina caldo cotone azzurra', 'Copertina culla ', 11.9, 'Privavera', 5.95),
	('A228', 'copertina ciniglia con orsetti', 'Copertina culla ', 19.9, 'Privavera', 9.95),
	('A229', 'copertina ciniglia verde prato', 'Copertina culla ', 9.9, 'Privavera', 4.95),
	('A23', 'tutina ciniglia melbi arancio', 'Tutina', 12.3, 'Inverno', 7.38),
	('A230', 'copertina caldo cotone giallo ', 'Copertina culla ', 8.6, 'Privavera', 4.3),
	('A231', 'copertina cotone azzurro', 'Copertina culla ', 9.9, 'Estate', 4.95),
	('A232', 'copertina filo di scozia cielo', 'Copertina culla ', 22.9, 'Estate', 11.45),
	('A233', 'copertina cotone piquè macchine', 'Copertina culla ', 15.9, 'Estate', 7.95),
	('A234', 'copertina cotone ricamata stelle', 'Copertina culla ', 12.9, 'Estate', 6.45),
	('A235', 'copertina seta con applicazioni', 'Copertina culla ', 45.9, 'Estate', 22.95),
	('A236', 'copertina seta con bottoni', 'Copertina culla ', 48.5, 'Estate', 24.25),
	('A237', 'copertina cotone egiziano bleu', 'Copertina culla ', 23.5, 'Estate', 11.75),
	('A238', 'lenzuolino lettino cotone giallo', 'Lenzuolino lettino', 9.9, 'Estate', 4.95),
	('A239', 'lenzuolino lettino cotone verde', 'Lenzuolino lettino', 10.9, 'Estate', 5.45),
	('A24', 'tutina ciniglia melbi verde', 'Tutina', 11.9, 'Inverno', 7.14),
	('A240', 'lenzuolino lettino orsetto', 'Lenzuolino lettino', 12.5, 'Estate', 6.25),
	('A241', 'lenzuolino lettino fantasia', 'Lenzuolino lettino', 13.9, 'Estate', 6.95),
	('A242', 'lenzuolino ricamato coccinelle', 'Lenzuolino lettino', 18.9, 'Estate', 9.45),
	('A243', 'lenzuolino lettino farfalle', 'Lenzuolino lettino', 8.6, 'Estate', 4.3),
	('A244', 'lenzuolino lettino con strass', 'Lenzuolino lettino ', 19.9, 'Estate', 9.95),
	('A245', 'lenzuolino lettino con rose', 'Lenzuolino lettino ', 22.9, 'Estate', 11.45),
	('A246', 'lenzuolino lettino con tulipani', 'Lenzuolino lettino ', 11.9, 'Estate', 5.95),
	('A247', 'lenzuolino lettino macramè', 'Lenzuolino lettino ', 35.6, 'Estate', 17.8),
	('A248', 'lenzuolino lettino fiori di pesco', 'Lenzuolino lettino ', 17.8, 'Estate', 8.9),
	('A249', 'lenzuolino lettino disney', 'Lenzuolino lettino ', 22.3, 'Estate', 11.15),
	('A25', 'tutina ciniglia melbi sole', 'Tutina', 14.2, 'Inverno', 8.52),
	('A250', 'lenzuolino lettino arcobaleno', 'Lenzuolino lettino ', 13.4, 'Estate', 6.7),
	('A251', 'lenzuolino lettino con fiori rosa', 'Lenzuolino lettino ', 9.9, 'Estate', 4.95),
	('A252', 'lenzuolino lettino con cuori rossi', 'Lenzuolino lettino ', 20, 'Estate', 10),
	('A253', 'lenzuolino lettino nuvola ', 'Lenzuolino lettino ', 45.9, 'Estate', 22.95),
	('A254', 'lenzuolino lettino in seta ', 'Lenzuolino lettino ', 58.9, 'Estate', 29.45),
	('A255', 'lenzuolino lettino con panda verde', 'Lenzuolino lettino ', 9.9, 'Estate', 4.95),
	('A256', 'lenzuolino lettino zoo', 'Lenzuolino lettino ', 7.5, 'Estate', 3.75),
	('A257', 'lenzuolino lettino pizzo francese', 'Lenzuolino lettino ', 48.7, 'Estate', 24.35),
	('A258', 'lenzuolino lettino macchine', 'Lenzuolino lettino ', 11.3, 'Estate', 5.65),
	('A259', 'lenzuolino  quadrifoglio verde', 'Lenzuolino lettino ', 13.8, 'Estate', 6.9),
	('A26', 'tutina ciniglia strass', 'Tutina', 29.9, 'Inverno', 17.94),
	('A260', 'lenzuolino lettino con orsi', 'Lenzuolino lettino ', 16.2, 'Estate', 8.1),
	('A261', 'lenzuolino lettino arcobaleno cielo', 'Lenzuolino lettino ', 9.4, 'Estate', 4.7),
	('A262', 'lenzuolino lettino con papere', 'Lenzuolino lettino ', 13.3, 'Estate', 6.65),
	('A263', 'lenzuolino lettino arancio', 'Lenzuolino lettino ', 8.5, 'Estate', 4.25),
	('A264', 'lenzuolino lettino ranocchio', 'Lenzuolino lettino ', 12.9, 'Estate', 6.45),
	('A265', 'lenzuolino lettino cane', 'Lenzuolino lettino ', 16.8, 'Estate', 8.4),
	('A266', 'lenzuolino lettino con pirati', 'Lenzuolino lettino ', 19.9, 'Estate', 9.95),
	('A267', 'lenzuolino lettino con barchette', 'Lenzuolino lettino ', 18.7, 'Estate', 9.35),
	('A268', 'lenzuolino lettino tema calcio', 'Lenzuolino lettino ', 10.5, 'Estate', 5.25),
	('A269', 'lenzuolino lettino flanella', 'Lenzuolino lettino', 12.4, 'Inverno', 6.2),
	('A27', 'tutina ciniglia perle', 'Tutina', 32.9, 'Inverno', 19.74),
	('A270', 'lenzuolino lettino flanella zoo', 'Lenzuolino lettino', 16.8, 'Inverno', 8.4),
	('A271', 'lenzuolino lettino flanella orsi', 'Lenzuolino lettino', 13.3, 'Inverno', 6.65),
	('A272', 'lenzuolino lettino flanella prato', 'Lenzuolino lettino', 15, 'Inverno', 7.5),
	('A273', 'lenzuolino lettino flanella giallo', 'Lenzuolino lettino', 7.5, 'Inverno', 3.75),
	('A274', 'lenzuolino lettino ricamato cielo', 'Lenzuolino lettino', 22.5, 'Inverno', 11.25),
	('A275', 'lenzuolino lettino ricamo fiori', 'Lenzuolino lettino ', 17.9, 'Inverno', 8.95),
	('A276', 'lenzuolino lettiuno caldo cotone', 'Lenzuolino lettino ', 14, 'Inverno', 7),
	('A277', 'lenzuolino lettino fiorato giallo', 'Lenzuolino lettino ', 16.2, 'Inverno', 8.1),
	('A278', 'lenzuolino lettino con rose', 'Lenzuolino lettino ', 25.7, 'Inverno', 12.85),
	('A279', 'lenzuolino lettino con strass', 'Lenzuolino lettino ', 33.8, 'Inverno', 16.9),
	('A28', 'tutina ciniglia due pezzi ', 'Tutina', 16.9, 'Inverno', 10.14),
	('A280', 'lenzuolino lettino con macchine', 'Lenzuolino lettino ', 9.9, 'Inverno', 4.95),
	('A281', 'lenzuolino lettino moto rosso', 'Lenzuolino lettino ', 16.7, 'Inverno', 8.35),
	('A282', 'lenzuolino lettino gufo cielo', 'Lenzuolino lettino ', 19.2, 'Inverno', 9.6),
	('A283', 'lenzuolino lettino tinta unita', 'Lenzuolino lettino ', 10.9, 'Inverno', 5.45),
	('A284', 'copertina lettino lana', 'Copertina lettino', 22.4, 'Inverno', 11.2),
	('A285', 'copertina lettino con stelle', 'Copertina lettino', 24.3, 'Inverno', 12.15),
	('A286', 'copertina lettino con ricami', 'Copertina lettino', 36.9, 'Inverno', 18.45),
	('A287', 'copertina lettino zoo', 'Copertina lettino', 25.9, 'Inverno', 12.95),
	('A288', 'copertina lettino arcobaleno', 'Copertina lettino', 15.9, 'Inverno', 7.95),
	('A289', 'copertina lettino pile', 'Copertina lettino', 9.9, 'Inverno', 4.95),
	('A29', 'tutina ciniglia due pezzi ', 'Tutina', 16.9, 'Inverno', 10.14),
	('A290', 'copertina lettino pile con orsi', 'Copertina lettino', 10.4, 'Inverno', 5.2),
	('A291', 'copertina lettino lana merinos', 'Copertina lettino', 45.5, 'Inverno', 22.75),
	('A292', 'copertina lettino pile rosa', 'Copertina lettino ', 8.8, 'Inverno', 4.4),
	('A293', 'copertina lettino ricamata rosa', 'Copertina lettino ', 33.5, 'Inverno', 16.75),
	('A294', 'copertina lettino con perle', 'Copertina lettino ', 56.8, 'Inverno', 28.4),
	('A295', 'copertina lettino con cuori', 'Copertina lettino ', 24.3, 'Inverno', 12.15),
	('A296', 'copertina lettino con paperette', 'Copertina lettino ', 13.5, 'Inverno', 6.75),
	('A297', 'copertina lettino con stampe', 'Copertina lettino ', 11.9, 'Inverno', 5.95),
	('A298', 'copertina lettino con pizzo', 'Copertina lettino ', 17.5, 'Inverno', 8.75),
	('A299', 'copertina lettino con frutta', 'Copertina lettino ', 8.2, 'Inverno', 4.1),
	('A3', 'tutina ciniglia ellepì Disney', 'Tutina', 12.99, 'Inverno', 7.79),
	('A30', 'tutina ciniglia due pezzi neutra', 'Tutina', 12, 'Inverno', 7.2),
	('A300', 'copertina lettino con margherite', 'Copertina lettino ', 19.4, 'Inverno', 9.7),
	('A301', 'copertina lettino con tulipani', 'Copertina lettino ', 22.3, 'Inverno', 11.15),
	('A302', 'copertina lettino coniglietto rosa', 'Copertina lettino ', 37.4, 'Inverno', 18.7),
	('A303', 'copertina lettino ciniglia fiorita', 'Copertina lettino ', 15, 'Inverno', 7.5),
	('A304', 'copertina lettino ciniglia con panda', 'Copertina lettino ', 12.4, 'Inverno', 6.2),
	('A305', 'copertina lettino trapuntata', 'Copertina lettino ', 27, 'Inverno', 13.5),
	('A31', 'tutina cotone ellepì', 'Tutina', 9.9, 'Privavera', 5.94),
	('A32', 'tutina cotone ellepì ricamata', 'Tutina', 13.5, 'Privavera', 8.1),
	('A33', 'tutina cotone ellepì ', 'Tutina', 11, 'Privavera', 6.6),
	('A34', 'tutina cotone ellepì ', 'Tutina', 11, 'Privavera', 6.6),
	('A35', 'tutina cotone arcobaleno ', 'Tutina', 12, 'Privavera', 7.2),
	('A36', 'tutina cotone arcobaleno ', 'Tutina', 12, 'Privavera', 7.2),
	('A37', 'tutina cotone spezzata ', 'Tutina', 9.9, 'Privavera', 5.94),
	('A38', 'tutina cotone spezzata ', 'Tutina', 9.9, 'Privavera', 5.94),
	('A39', 'tutina cotone mek delux ', 'Tutina', 16.9, 'Privavera', 10.14),
	('A4', 'tutuna ciniglia ellepì mod. Sole', 'Tutina', 10.9, 'Inverno', 6.54),
	('A40', 'tutina cotone mek delux ', 'Tutina', 16.9, 'Privavera', 10.14),
	('A41', 'tutina cotone stella', 'Tutina', 7.5, 'Privavera', 4.5),
	('A42', 'tutina cotone fiori', 'Tutina', 5.5, 'Privavera', 3.3),
	('A43', 'tutina cotone Firenze', 'Tutina', 18.9, 'Privavera', 11.34),
	('A44', 'tutina cotone Venezia', 'Tutina', 22.5, 'Privavera', 13.5),
	('A45', 'pagliaccetto ', 'Tutina', 6.3, 'Estate', 3.78),
	('A46', 'pagliaccetto ', 'Tutina', 6.3, 'Estate', 3.78),
	('A47', 'pagliaccetto frutta ', 'Tutina', 7.7, 'Estate', 4.62),
	('A48', 'pagliaccetto s/l ', 'Tutina', 8, 'Estate', 4.8),
	('A49', 'pagliaccetto s/l ', 'Tutina', 8, 'Estate', 4.8),
	('A5', 'tutina ciniglia ellepì art. 122', 'Tutina', 13.9, 'Inverno', 8.34),
	('A50', 'pagliaccetto ellepì ', 'Tutina', 9, 'Estate', 5.4),
	('A51', 'pagliaccetto ellepì ', 'Tutina', 9, 'Estate', 5.4),
	('A52', 'pagliaccetto zucchi ricamato', 'Tutina', 13.5, 'Estate', 8.1),
	('A53', 'pagliaccetto zucchi fiori', 'Tutina', 9.9, 'Estate', 5.94),
	('A54', 'pagliaccetto zucchi erba', 'Tutina', 9.9, 'Estate', 5.94),
	('A55', 'pagliaccetto chicco ', 'Tutina', 14, 'Estate', 8.4),
	('A56', 'pagliaccetto chicco ', 'Tutina', 14, 'Estate', 8.4),
	('A57', 'pagliaccetto neutro', 'Tutina', 5.5, 'Estate', 3.3),
	('A58', 'pagliaccetto millionair', 'Tutina', 25.9, 'Estate', 15.54),
	('A59', 'pagliaccetto balze ', 'Tutina', 12.2, 'Estate', 7.32),
	('A6', 'tutina ciniglia ellepì art. 125', 'Tutina', 16.5, 'Inverno', 9.9),
	('A60', 'pagliaccetto filo di scozia', 'Tutina', 18.5, 'Estate', 11.1),
	('A61', 'body felpa m/l ', 'Body', 3.5, 'Inverno', 1.75),
	('A62', 'body felpa ', 'Body', 3.5, 'Inverno', 1.75),
	('A63', 'body felpa assortito ', 'Body', 5, 'Inverno', 2.5),
	('A64', 'body felpa Disney ', 'Body', 4.5, 'Inverno', 2.25),
	('A65', 'body felpa Disney ', 'Body', 4.5, 'Inverno', 2.25),
	('A66', 'body m/m felpa ', 'Body', 3, 'Inverno', 1.5),
	('A67', 'body felpa m/m ', 'Body', 3, 'Inverno', 1.5),
	('A68', 'body felpa m/m  stampato', 'Body', 3.8, 'Inverno', 1.9),
	('A69', 'body cotone m/l ', 'Body', 4.5, 'Privavera', 2.25),
	('A7', 'tutina ciniglia zucchi', 'Tutina', 6.9, 'Inverno', 4.14),
	('A70', 'body cotone m/l ', 'Body', 4.5, 'Privavera', 2.25),
	('A71', 'body cotone m/l stampato', 'Body', 5.5, 'Privavera', 2.75),
	('A72', 'body cotone m/m bianco', 'Body', 4, 'Privavera', 2),
	('A73', 'body cotone m/m ', 'Body', 4.5, 'Privavera', 2.25),
	('A74', 'body cotone m/m ', 'Body', 4.5, 'Privavera', 2.25),
	('A75', 'body cotone m/m Disney ', 'Body', 5.5, 'Privavera', 2.75),
	('A76', 'body cotone m/m Disney ', 'Body', 5.5, 'Privavera', 2.75),
	('A77', 'body cotone m/m bottoni', 'Body', 3.5, 'Privavera', 1.75),
	('A78', 'body cotone m/m strappo', 'Body', 4, 'Privavera', 2),
	('A79', 'body cotone s/l bianco', 'Body', 3.5, 'Estate', 1.75),
	('A8', 'tutina ciniglia zucchi ricamata', 'Tutina', 12.9, 'Inverno', 7.74),
	('A80', 'body cotone s/l ', 'Body', 4, 'Estate', 2),
	('A81', 'body cotone s/l ', 'Body', 4, 'Estate', 2),
	('A82', 'body cotone s/l ricamato ', 'Body', 6.5, 'Estate', 3.25),
	('A83', 'body cotone s/l Disney ', 'Body', 5, 'Estate', 2.5),
	('A84', 'body cotone s/l Disney ', 'Body', 5, 'Estate', 2.5),
	('A85', 'body cotone s/s bianco ', 'Body', 5.5, 'Estate', 2.75),
	('A86', 'body cotone s/s Disney ', 'Body', 6, 'Estate', 3),
	('A87', 'body lupetto m/l felpa bianco', 'Body', 6.8, 'Inverno', 3.4),
	('A88', 'body lupetto m/l felpa colorato', 'Body', 7.5, 'Inverno', 3.75),
	('A89', 'body lupetto m/l felpa Disney ', 'Body', 8.5, 'Inverno', 4.25),
	('A9', 'tutina ciniglia zucchi  ', 'Tutina', 12.9, 'Inverno', 7.74),
	('A90', 'body lupetto m/l felpa Disney ', 'Body', 8.8, 'Inverno', 4.4),
	('A91', 'ghettina felpa bianco', 'Ghettina', 2.5, 'Inverno', 1.63),
	('A92', 'ghettina felpa colorato', 'Ghettina', 3.5, 'Inverno', 2.28),
	('A93', 'ghettina felpa fantasia fiori', 'Ghettina', 3.8, 'Inverno', 2.47),
	('A94', 'ghettina felpa bianco economica', 'Ghettina', 1.8, 'Inverno', 1.17),
	('A95', 'ghettina cotone bianco', 'Ghettina', 2.8, 'Privavera', 1.82),
	('A96', 'ghettina cotone fantasia', 'Ghettina', 3.5, 'Privavera', 2.28),
	('A97', 'ghettina cotone macchine', 'Ghettina', 3.5, 'Privavera', 2.28),
	('A98', 'ghettina cotone stella', 'Ghettina', 4, 'Privavera', 2.6),
	('A99', 'ghettina con pizzo ', 'Ghettina', 6.8, 'Privavera', 4.42);
/*!40000 ALTER TABLE `listino` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
